common: &default_session
  options:
    write:
     w: 1
    read: primary
    max_retries: <%= ENV['MONGOID_MAX_RETRIES'] || 1 %>
    retry_interval: <%= ENV['MONGOID_RETRY_INTERVAL'] || 0 %>
    timeout: <%= ENV['MONGOID_TIMEOUT'] || 0.5 %>
    ssl: <%= ENV['MONGOID_USE_SSL'] || false %>

common_uri: &default_uri
  uri: <%= ENV['MONGOHQ_URL'] %>

development:
  clients:
    default:
      <<: *default_client
      database: cs_comments_service_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      <<: *default_session
      database: cs_comments_service_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      <<: *default_uri
      <<: *default_session

edgeprod:
  clients:
    default:
      <<: *default_uri
      <<: *default_session

edgestage:
  clients:
    default:
      <<: *default_uri
      <<: *default_session

staging:
  clients:
    default:
      <<: *default_uri
      <<: *default_session

loadtest:
  clients:
    default:
      <<: *default_uri
      <<: *default_session

defaults: &defaults
  use_utc: false
  use_activesupport_time_zone: true
